FROM node:18-alpine

# Set the working directory to /usr/src/app
WORKDIR /usr/src/app

# Set environment to development
ENV NODE_ENV=development

# Copy package.json files into the working directory
COPY client/package*.json ./

# Install dependencies with verbose output
RUN npm install --verbose

# Copy the rest of your client directory into the working directory
COPY client/ ./

# Expose port 3000 for the application
EXPOSE 3000

# Command to run the development server
CMD ["npm", "run", "dev"]
