services:
  react:
    build:
      context: .
      dockerfile: Dockerfile-react
    volumes:
      - ./client:/usr/src/app
      - react_node_modules:/usr/src/app/node_modules
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
  app:
    build:
      context: .
      dockerfile: Dockerfile-flask
    volumes:
      - ./server:/app
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development

volumes:
  react_node_modules:
    driver: local
